#+title: Simulated Annealing Position Allocation Problem Paper
#+autor: Alexander Brown
#+date: \today

This paper discusses the research behind the Simulated Annealing (SA) approach to solving the Position Allocation
Problem (PAP). This paper is based off the theory of SA as well as some of my previous work on the PAP. The SA algorithm
is utilized as a means of generating candidate solutions that will be against one another. The quality of the solution
is dictated by the objective function derived in [[https://github.com/alexb7711/milp-pap-paper-frontiers][MILP PAP]]. Also, to ensure that the generated solutions are realistic,
the SA-PAP utilizes the same constraints as [[https://github.com/alexb7711/milp-pap-paper-frontiers][MILP PAP]] as a way of verifying that solutions generated by the SA algorithm
are in the solution space.

* Artifacts and Releases
:PROPERTIES:
:CUSTOM_ID: sec:artifacts-and-releases
:END:

** Peer Reviews
:PROPERTIES:
:CUSTOM_ID: sec:peer-reviews
:END:
If you are viewing this to review the latest revision from the =main= branch, then it is *highly* recommended that you
run =make pipeline= to generate a PDF with the version embedded in the PDF (see [[*Building the Paper][Building the Paper]]).

** Releases
:PROPERTIES:
:CUSTOM_ID: sec:releases
:END:
If you are reading this from the release notes then the PDF associated with the release will have a version (same as the
git tag from the given commit). This is done to be able to easily track what version of the document is being released
and reviewed.

* Building the Paper
:PROPERTIES:
:CUSTOM_ID: sec:building-the-paper
:END:
The document is written in [[https://orgmode.org/][org mode]] and is thus primarily generated via the export functions in Emacs; however, the
=LaTeX= file generated from the =org= document is included in the repository which can also be built from. Since that
file is regenerated every time the PDF is generated, the =LaTeX= file /should/ be up-to-date with =org= changes.

With that being said. The required programs are a full instalation of =LaTeX= as well as [[https://mg.readthedocs.io/latexmk.html][latexmk]] and =pdflatex=.

It is recommended to have [[https://www.gnu.org/software/make/][GNU Make]] installed to automate the build process. Type =make help= for a list of commands.
