################################################################################
# ENVIRONTMENT
################################################################################
version: '3'

env:
  TARGET : sa-pap.pdf
  IMG_DIR: ./sections/img/
  DOC    : main
  SCRIPTS: org-doc-scripts

################################################################################
# RECIPES
################################################################################

tasks:

##==============================================================================
#
  default:
    cmds:
      - task: precheck
      - task: pdf

##==============================================================================
#
  pipeline:
    cmds:
      - task: precheck
      - task: set-version
      - task: pdf

##==============================================================================
#
  precheck:
    desc: "Make sure that all the dependencies are installed."
    cmds:
      - sh {{.SCRIPTS}}/check-packages
    silent: true

##==============================================================================
#
  images:
    desc: "Creates a PDF of all the files in {{.IMG_DIR}}."
    sources:
      - ./img/*.pml
    generates:
      - ./img/*.png
    vars:
      IMG_SRC:
        sh: ls {{.IMG_DIR}} | grep ".pml"
    cmds:
      - |
        for f in {{.IMG_SRC | catLines}}
        do
          if [ $f != "general_yaml.pml" ] && [ $f != "route_yaml.pml" ]
          then
            echo "Compiling ${f}"
            plantuml -tpng {{.IMG_DIR}}/${f}
          fi
        done
    silent: true

##==============================================================================
#
  set-version:
    desc: "Dynamically sets the version of the document."
    vars:
      MAIN: main.tex
      VERSION:
        sh: git describe --tags
    cmds:
      - |
        sed -i 's/\\date{\\today/\\date{\\today:{{.VERSION}}/' {{.MAIN}}
    silent: true

##==============================================================================
#
  relative-path-bibtex:
    desc: "Update the paths in the 'bibtex' command to be relative."
    cmds:
      - sh {{.SCRIPTS}}/relative-path-bibtex {{.DOC}}.tex

##==============================================================================
#
  pdf:
    desc: "Output {{.TARGET}} PDF."
    sources:
      - ./*.tex
    generates:
      - ./sa-pap.pdf
    cmds:
      - task: relative-path-bibtex
      - sh {{.SCRIPTS}}/build-pdf {{.DOC}} {{.TARGET}}
    silent: false

##==============================================================================
#
  clean:
    desc: "Clean up the project."
    vars:
      DOC_SRC: main.tex
    cmds:
      - |
        # Clean up {{.IMG_DIR}}
        for f in $(find {{.IMG_DIR}} -maxdepth 1 -type f)
        do
          [ ${f##*.} != "pml" ] && [ ${f##*.} != "jpg" ] && [ ${f##*.} != "org" ]  && rm ${f}
        done
        # Clean up the document files
        rm -f {{.TARGET}}
        latexmk -silent -c {{.DOC_SRC}}
    silent: true
