** Conclusion
:PROPERTIES:
:custom_id: sec:conclusion
:END:

This work developed an SA implementation derived from the works of the MILP PAP. The model is designed to reduce the
total number of utilized chargers, minimize the peak energy consumption and the total energy consumed. The problem
description was provided outlining the scenario in which this model is designed for. The optimization problem was then
introduced by describing the components of the objective function and outlining the MILP constraints utilized to ensure
candidate solutions are in the solution space.

The objective function is composed of two main pieces: the assignment cost and the utility cost. The assignment cost
consists of the cost of assigning a BEB to a particular queue. The cost of assigning a BEB to an idle queue (a queue
that provides no charge) has no cost. However, the cost of assigning a BEB to a charge queue, ordered first by slow then
fast chargers, is scaled by a constant gain factor multiplied by the queue index. The assignment cost also composes of
the penalty method designed to keep the SOC above a specified charge threshold. If the initial SOC of a BEB upon arrival
to the station is below the threshold, a large penalty is applied to the objective. The utility cost consists of the
consumption cost and the demand cost. The consumption cost is the total accumulated energy of the schedule and the
demand cost is described by the peak 15.

An example of the SA PAP algorithm was then presented and compared the MILP PAP and Qin-Modified techniques. The SA PAP
was run utilizing two different neighborhood searching techniques named the quick and exhaustive techniques,
respectively. The quick SA's objective was to randomly search a wide neighborhood while the exhaustive technique was
designed to incrementally search the neighborhood by randomly selecting a fast or slow charging queue and then stepping
through the queues one at a time. The quick and exhaustive have comparable run times at src_latex{\fpeval{\quicklocal *
\tempcnt}} seconds and src_latex{\fpeval{\exhaustivelocal * \tempcnt}} seconds, repressively. The Qin-Modified and MILP
PAP utilized the fewest amount of chargers. The exhaustive SA technique generated a solution resembling that of the MILP and Qin-Modified, but was unable to minimize the charger count as efficiently. The quick SA utilized all the chargers available.

Both of the SA techniques were unable to keep the SOC above the 25% SOC threshold. Both techniques had the SOC fall to
about 50 kW; however, the quick technique fell to the 50 kW mark during the time horizon while the exhaustive only reach
the 50 kW mark at the end of the working day. The Qin-Modified had the SOC of three BEBs fall to 0% SOC. The MILP PAP,
on the other hand, has a constraint requiring the SOC to stay above an SOC of 25% which was reflected in schedule.

The power and energy consumption of each of the models was then compared. The peak power usage of the exhaustive SA,
Qin-Modified, and MILP PAP had comparable peaks in power consumption; whereas the quick SA had the largest peak. The
power consumption of the exhaustive SA was similar to that of the Qin-Modified which were both less than the MILP PAP.
As for the accumulated energy consumption, the MILP PAP performed the worst. This is accounted for by a constraint that
requires the SOC of each BEB to be above a 70% SOC. The schedule that consumed the least amount of energy is the
exhaustive SA. The total range of energy consumption is about $0.4 \cdot 10^4$ kWh.

Further fields of interest are to investigate the performance of the quick and exhaustive SA approaches utilizing a denser
set of routes to schedule. It is also of interest to incorporate non-linear battery dynamics to more accurately model
the SOC. Furthermore, "fuzzifying" the charge times is of interest to allow flexibility in the initial and final charge
times for each BEB visit.
