# ################################################################################
# LINKS:
#
# https://github.com/maxbw117/DevelopmentPerSecond/blob/master/Tikz-pgfplots-and-latex/Tutorial#202-#20Figures#20and#20Large#20File#20Organization/Figures#20Chapter#201/01#20Ocean#20and#20Model#20Scale.TeX
# https://www.overleaf.com/learn/latex/Questions/I_have_a_lot_of_tikz#2C_matlab2tikz_or_pgfplots_figures#2C_so_I#27m_getting_a_compilation_timeout._Can_I_externalise_my_figures#3F
# ################################################################################

* Example
:PROPERTIES:
:custom_id: sec:example
:END:

An example is now provided to demonstrate the utility of the developed SA charge scheduling technique. In
[[#sec:beb-scenario]] a description of the example scenario is presented followed by a brief introduction of the original
MILP PAP. An alternative heuristic based planning strategy called Qin-Modified, and a heuristic modification to the SA
PAP are also used as comparisons to the SA PAP technique presented in this work. [[#sec:results]] presents the results for
each of planning strategies. The results are also analyzed and discussed.

** BEB Scenario
:PROPERTIES:
:custom_id: sec:beb-scenario
:END:

The test scenario was run over a time horizon of $T=24$ hours, with a total of $n_V = \N$ visits to the station shared
between $n_B = \A$ buses. Each BEB has a battery capacity of $\kappa_b =$ \batsize kWh battery that is required to stay above
an SOC of $\nu_b =$ \mincharge (\fpeval{\batsize * \minchargeD} kWh). Each bus is assumed to begin the working day with $\alpha
=$ \fpeval{\acharge*100}% charge (\fpeval{\acharge * \batsize} kWh). Each bus is also assumed have a rate of discharge
of $\Delta =$ 30 kW. The penalty method employs a gain of $D = \Cgain$. A total of $n_C =$ \fpeval{\fast + \slow} chargers
are utilized where \slow of the chargers are slow charging (\slows kW) and \fast are fast charging (\fasts kW). As
previously introduced, to encourage the SA PAP to utilize the fewest number of chargers, the value of $\epsilon_q$ in the
objective function is $\forall q \in \{1,2,..., n_B \}; \epsilon_q = 0$ and $\forall q \in Q \setminus B; \epsilon_q = 100q$. The SA algorithm utilizes the
geometric cooling schedule with an initial temperature of $T_0 = \tempinit$ with $\beta_2 = 0.999$, resulting in a total of
$n_M = \tempcnt$ steps. The demand cost is taken over fifteen minute intervals. Thus let the demand cost be denoted as
the peak-15 with the associated symbol $p_{15}$. A weight vector of $[3, 3, 2, 1]$ was used to influence the
distribution of selecting the new charger, new window, wait, and slide visit primitives, respectively. The algorithm
also assumes a total of $n_K = \localcnt$ iterations for the local search at a constant temperature. In total, that
results in src_latex{\fpeval{\localcnt * \tempcnt}} configurations being searched. On average each constant temperature
search took an average of $\quicklocal$ seconds to complete, resulting in a total runtime of
src_latex{\fpeval{\quicklocal * \tempcnt}} seconds.

[[#sec:heuristic-implementation]] introduced the idea of an alternative heuristic implementation for the SA algorithm. To
distinguish the heuristic implementation from the method derived in [[#sec:generation-mechanisms]], let this implementation
be referred to as "heuristic" implementation and the previous as the "quick" implementation. Using the same weights for
selecting randomly selecting the primitive generators, the heuristic approach further implemented a weighted
distribution vector of $[3, 1]$ to decide whether to select a slow or fast charger, respectively. In the heuristic
approach, on average the constant temperature search took a total of $\heuristiclocal$ seconds to complete, resulting in
a total runtime of src_latex{\fpeval{\heuristiclocal * \tempcnt}} seconds. The heuristic generators were expected to be
slightly slower due to its iterative approach.

One of the methods utilized to compare with the SA PAP is the MILP PAP. This framework is the original MILP
implementation of the PAP derived from [cite:@qarebagh-2019-optim-sched]. The inputs to the system are the same as those
discussed above. The MILP PAP does not implement the peak-15 in its objective function. In an attempt to compare the
solution of the MILP with the SA output more directly, a similar solve time of 3600 seconds. The MILP was executed
utilizing the Gurobi MILP solver [cite:@gurobi-2021-gurob-optim].

Another heuristic-based optimization strategy, referred to as Qin-Modified, is also employed as a means of comparison
with the results of the SA PAP. The Qin-Modified algorithm is a based on the threshold strategy of
[cite:@qin-2016-numer-analy]. The algorithm has been modified slightly to accommodate the case of multiple charger types
without a heuristic search for the best charger type. The heuristic is based on a set of rules that revolve around the
initial charge of the bus at visit $i$. There are three different thresholds, low (85%), medium (90%), and high (95%).
Buses below the low threshold are prioritized to fast chargers then are allowed to utilize slow chargers if no fast
chargers are available. Buses between the low and medium threshold prioritize slow chargers first and utilize fast
chargers only if no slow chargers are available. Buses above the medium threshold and below high will only be assigned
to slow chargers. Buses above the high threshold will not be charged. Once a bus has been assigned to a charger, it
remains on the charger for the duration of the time it is at the station, or it reaches 95% charge, whichever comes
first. Note that UTA uses 70% to decide that a fast charger is required. The previously described simulations were run
on a machine equipped with an AMD Ryzen 9 5900X 12 - Processor (24 core) at 4.95GHz.


** Results
:PROPERTIES:
:custom_id: sec:results
:END:

The schedules generated by each of the methods is presented in \ref{fig:schedule}. Rows 0-14 represent slow charging
queues and rows 15-29 represent fast charging queues. The symbols represent the initial charge times, and the horizontal
line with the vertical tick signifies the region of time the charger is active. A qualitative comparison between the
different is the perceived lack of organization of the quick SA technique. Although the assignment cost was set in
place, due to the random nature of the queue assignments the simulation was not able to converge to a well-packed
solution. The heuristic approach was able to more successfully able to pack its schedule similarly to the schedule of
the Qin-Modified and MILP PAP.

On the quantitative side of the minimization/packing discussion, the Qin-Modified schedule utilizes one fast and two
slow chargers as can be seen in \ref{subfig:schedule-qin}. The MILP PAP framework generated a schedule that utilizes
three fast charges and four slow chargers as shown in \ref{subfig:schedule-milp}. The heuristic SA strategy created its
schedule with eight slow charger queues and four fast charging queues as shown in \ref{subfig:schedule-heuristic-sa}.
The quick strategy for the SA algorithm created a schedule utilizing fifteen slow and fast chargers as is demonstrated
in \ref{subfig:schedule-quick-sa}. That is to say, the Qin-Modified schedule was able to most effectively minimize the
charger count followed by the MILP PAP, and the heuristic SA, and the work being the quick SA technique. The MILP
produced a schedule with a three charger gap in the fast queues, where the intermediate queues were never used. The
heuristic SA, while possibly being able to move some assignments to a lower charge queue index, did not contain any gaps
of unused queues. The Qin-Modified utilized the fewest chargers overall, but also suffers a lack of optimality in its
packing of the schedule. Thus, none of the methods were able to fully minimize the packing constraint. Note that the SA
algorithm has no guarantee of optimality; therefore, post-processing could be applied to further minimize the charger
indices.

A table of the mean, maximum instantaneous charger use is shown in \ref{tab:charge-count}. The mean is meant to be a
measure of how many slow/fast chargers are being utilized over the time horizon, on average. The maximum and scheduled
rows represent the total amount of queues the system actually utilized in parallel while the scheduled queues represents
the amount of queues a particular schedule calls for. The Qin-Modified only utilized 2 slow chargers, so the mean is
expected to be low (0.788). The quick SA technique utilized every slow charger, but only utilized a mean use of 1.494
chargers with a maximum of only six chargers. This indicates that although all the queues were used, on average only
1.494 queues were required with a peak of six slow queues required to be use in parallel. Thus, with appropriate
packing, only six queues were actually required. Similarly, the MILP on average used 1.877 chargers with a maximum of 4
being used at any given moment, which is the same as the required amount of queues by the schedule. The heuristic SA had
a mean of 1.8 chargers utilized with a maximum of seven chargers utilized, although the total queues required by the
schedule is nine. As stated before, SA will never find the optimum solution; thus, it is to be expected to have
non-optimal assignments.

Similarly, the fast chargers, the Qin-Modified all the queues were utilized but only a mean instantaneous use of 0.234
chargers were used at any given moment with a maximum of two chargers. The MILP calls for a total of three queues, but
only ever has a maximum use of two with a mean of 0.133 chargers utilized at any given moment over the time horizon. The
heuristic SA technique had a required four fast charging queues, but used at most two at a given moment. The average use
over the time horizon was 0.159 fast chargers. That is, both the MILP and heuristic SA schedules could have been further
minimized given the same schedule.

#+include: tab/charge-count.org

\ref{fig:charge} depicts the initial SOC for each visit throughout the simulation of each framework. \ref{tab:charge}
tabulates the mean, minimum, and maximum SOC upon arrival for each visit. The MILP PAP requires each BEB to stay above
an SOC of 25% while the quick and heuristic SA approaches heavily penalize a schedule for allowing a BEB to go below the
25% SOC threshold. The MILP PAP was able to successfully keep the SOC above the threshold (\ref{subfig:milp-charge})
while both SA approaches were not. The SOC of the quick SA approach dropped to a minimum of 29.9 kWh and the heuristic
had a minimum SOC of 6.3 kWh as shown in \ref{tab:charge}. The Qin model allowed the SOC of three BEBs to reach an SOC
of 0% as shown in \ref{subfig:qin-charge}. The Qin-Modified strategy was able to keep the mean SOC the highest followed
by the quick SA, heuristic SA, and then the MILP. This measure is useful when viewing with \ref{fig:power} and
\ref{fig:energy-usage}.

#+include: tab/charge.org

\ref{fig:power} depicts the power consumption over the time horizon for each model. As previous stated, the Qin-Modified
schedule had the highest mean SOC over the working day. Referencing \ref{fig:power-usage-milp-qin}, the Qin, while
staying below 1000 kW, is held at that level of power consumption for long periods of time. Similarly, the quick SA,
heuristic SA, and the MILP show that as the average SOC goes down, so does the demand. That is, if a schedule has a
lower average SOC, the required demand (and total energy consumption which will be discussed shortly) is also lower.

\ref{fig:power} is also of interest as it plots the peak power demand over the time horizon. The peaks in descending
order are the quick and heuristic SA are tied at 119.9 kW, the MILP at 1910 kW, and then the Qin at 970 kW. Although the
Qin had the lowest peak, it is again worth noting at this point that the Qin-Modified technique was unable to keep the
SOC above 0%. Thus, the MILP and quick and heuristic SA are comparable in terms of the demand cost. However, when
viewing the mean power consumption in descending order paints a different picture. The largest mean power demand is the
Qin-Modified at 424.95 kW, quick SA at 257.98 kW, heuristic SA at 198.84 kW, and then the MILP at 177.34 kW. The
Qin-Modified, as shown in \ref{fig:power-usage-milp-qin}, although having the lowest peak, holds the power for a long
duration as previously discussed. This measure directly correlates into the energy consumed by each schedule.

#+include: tab/power.org

The total energy consumed by each schedule is shown in \ref{fig:energy-usage}. The ordering of most energy consumed to
least is as follows: Qin-Modified, quick SA, heuristic SA, and the MILP PAP. The respective energy consumption for each
technique is: 10198.799 kWh, 6303.1704 kWh, 5785.76 kWh, and 4797.746 kWh. The heuristic SA consuming about 988 kWh more
than the MILP PAP.

* Footnotes

[fn:2] Remove when new data is applied.
