* Introduction
:PROPERTIES:
:CUSTOM_ID: sec:introduction
:END:

This document outlines a Simulated Annealing (SA) approach to the bus charging scheduling problem that utilizes Mixed
Integer Linear Programming (MILP) constraints to determine feasible charging schedules. The problem involves generating
an optimal charging schedule for a fleet of Battery Electric Buses (BEBs) based on a set of routes and a mix of fast and
slow chargers. The aim is to minimize both the consumption cost (amount of electricity used over a certain time) and the
demand cost (rate at which electricity is being used) while ensuring that the buses maintain sufficient charge to
complete their workday without delays.

The SA algorithm is introduced and constrained by a set of MILP constraints derived from the Position Allocation Problem
(PAP) to ensure the validity of proposed charging schedules. Objective functions describing consumption cost and demand
cost are used to minimize power consumption and total cost of using the BEBs.

#+begin_comment
*:DELETEME: This stuff is more relevant in a literature review :DELETEME:*

It is assumed that each visit occurs within the planning time horizon $T = \{t : t_0 \le t \le t_f \}$. The concept of
"arrivals" is derived from the PAP [cite:@qarebagh-2019-optim-sched]. The notion of a visit is useful in the sense that
it provides simple mechanism to describe the state of any arbitrary BEB at the time of arrival; however, a BEB may visit
the station multiple times. The issue arises due to model's assumption that each arrival is unique (i.e. no single BEB
arrives more than once). Therefore, a system must be put in place to track each BEB across visits.
#+end_comment
