* Introduction
:PROPERTIES:
:CUSTOM_ID: sec:sa-introduction
:END:

With an ever-increasing interest in the electrification of vehicles in the push for green transportation, many
organizations and companies have been looking to adopt a fleet of electric vehicles [cite:@khan-2022-inves]. This
transition is also stemming into the electrification of public bus transportation via battery power, i.e., battery
electric buses (BEBs) [cite:@li-2016-batter-elect;@guida-2017-zeeus-repor-europ]. In particular, agencies such as the
Utah Transit Authority (UTA) have directed focus in replacing their fleets with BEBs. Alongside all the benefits that
are associated with BEBs come new challenges that must be addressed prior to their integration into mainstream
utilization. The energy storage capacity of BEBs is typically significantly less than their combustion counterparts
while also having significantly longer refueling periods [cite:@xylia-2018-role-charg;@li-2016-batter-elect]. This is
further complicated due to the care that must be taken in prolonging the lifespan of the battery
[cite:@lutsey-2019-updat-elect;@edge-2021-lithium; @millner-2010-model-lithium]. As another complication, BEB refueling
is not a fixed cost (i.e. price per gallon multiplied by tank size). Utility companies, in addition to charging for the
total energy consumed over a pay period, often charge a demand cost. The demand cost is based on the peak power drawn
during the pay period and can significantly impact the overall monetary cost of maintaining the BEBs. This work
introduces a scheduling framework for a fleet of BEBs that minimizes charging costs while considering other constraints
pertinent for operation.

Works concerning charge planning often use a version of the vehicle scheduling problem [cite:@zhang-2021-optim-elect;
@duan-2021-refor-mixed; @rinaldi-2020-mixed-fleet; @tang-2019-robus-sched; @li-2014-trans-bus; @he-2020-optim-charg],
while others have based their implementation on alternative methods
[cite:@qarebagh-2019-optim-sched;@whitaker-2023-a-network]. [cite:@whitaker-2023-a-network] utilizes a network flow
approach to model the scheduling while [cite:@qarebagh-2019-optim-sched] utilizes what is known as the Position
Allocation Problem (PAP). The vehicle scheduling problem and the work of [cite:@whitaker-2023-a-network] involve the
discretization of the time horizon, whereas the PAP models the charge durations in a continuous manner reducing the
variable count. Regardless of the method utilized, nearly all the literature reviewed considers consumption costs
[cite:@jahic-2019-preem; @frendo-2021-open-sourc; @qin-2016-numer-analy; @zhou-2020-bi-objec; @duan-2021-refor-mixed;
@mortensen-2023-cost-minim; @zhou-2020-collab-optim; @rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim], while fewer
consider demand costs [cite:@jahic-2019-preem; @frendo-2021-open-sourc; @qin-2016-numer-analy;
@mortensen-2023-cost-minim; @he-2020-optim-charg]. Many of these works introduce simplifying assumptions for the sake of
computation. For example, some approaches only consider fast chargers during planing [cite:@zhou-2020-collab-optim;
@li-2014-trans-bus; @wang-2017-optim-rechar; @sebastiani-2016-evaluat-elect; @wei-2018-optim-spatio]. Approaches that
consider more than one charger type typically isolate the specific charger types in different locations
[cite:@tang-2019-robus-sched; @he-2020-optim-charg].

When considering battery charging, some works have assumed that BEBs always charge to full capacity
[cite:@duan-2021-refor-mixed; @zhang-2021-optim-elect; @zhou-2020-bi-objec; @wang-2017-elect-vehic], partial charging
utilizing a linear battery dynamics model [cite:@wei-2018-optim-spatio; @he-2020-optim-charg;
@mortensen-2023-cost-minim], or non-linear battery dynamics with partial charging [cite:@whitaker-2023-a-network;
@zhang-2021-optim-elect; @qin-2016-numer-analy; @jahic-2019-preem; @frendo-2021-open-sourc]. Works that assumed
scheduled BEBs always charge to full capacity significantly simplify the scheduling problem, but eliminates the key
factor in reducing the demand cost, partial charging [cite:@tang-2019-robus-sched; @duan-2021-refor-mixed;
@rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim].

# The approaches that utilized non-linear charging profiles with
# partial charging are able to achieve a reduction in the demand cost, with the added benefit of a higher fidelity at the
# expense of computation [cite:@zhang-2021-optim-elect]. Exceptions to this are [cite:@he-2020-optim-charg] that utilize a
# piecewise-linear charging profiles. This model has the drawback of assuming that a charger is always available.
# [cite:@whitaker-2023-a-network] proposes a discrete linear time-invariant dynamic model that results in an exponential
# decay non-linear charge profile.

The selected model for the battery charge dynamics, although pertinent to this work as it directly affects the quality
of the produced schedule, does not impact the considerations of battery health. Battery health begins to be of concern
when over-charging, under-charging, utilizing fast chargers extensively, or forcing the battery to perform "deep" cycles
[cite:@zhou-2020-bi-objec; @millner-2010-model-lithium; @edge-2021-lithium]. Furthermore, other works have suggested
that charging a battery nearly to capacity is detrimental to the health and can significantly reduce the total charge
cycles a battery may undergo [cite:@edge-2021-lithium; @millner-2010-model-lithium]. Thus, this work assumes that a
linear model is sufficiently accurate to produce an operationally valid schedule while maintaining battery health.

# While the charge profile for
# batteries are inherently non-linear, some works have assumed proportional charging as linear battery dynamics remain a
# valid assumption when the battery SOC is below 80% [cite:@liu-2020-batter-elect]. Thus, this work assumes that a linear
# model is sufficiently accurate to produce an operationally valid schedule while maintaining battery health.

In respect to the state of the art provided, this work aims to expand on the PAP by introducing a Simulated Annealing
(SA) framework that utilizes a proportional battery dynamics model, considers battery health by encouraging slow charger
use, allows for partial charging, allows for multiple charger types, minimizes consumption cost, and minimizes demand
cost. These contributions are demonstrated via simulation and comparison to two other models: the implementation of the
PAP for BEBs and what is known as the Qin-Modified technique.

The remainder of this paper goes as follows. [[#sec:sa-problem-description]] provides the problem statement associated with
this work. [[#sec:sa-optimization-problem]] provides a description of the input parameters and decision variables then
introduces the structure of the formulation. In [[#sec:sa-simulated-annealing]], the concept and theory of SA is introduced.
In particular, the algorithms and methods utilized for the SA implementation for this work are discussed.
[[#sec:sa-optimization-algorithm]] combines the previous sections to introduce the particular pseudocode for the SA PAP. In
[[#sec:sa-example]], an example problem is provided to demonstrate the capability of the work provided in this paper. The
results will be presented and discussed.

#+begin_comment
Literature shows an interest in solving the problem of assigning BEBs to charging queues or optimizing their
infrastructure [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;
@hoke-2014-accoun-lithium;@wang-2017-elect-vehic]. Additionally, the prospect of solving both problems simultaneously
has received much attention [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;
@hoke-2014-accoun-lithium;@wang-2017-elect-vehic]. These problems vary by including assignment of buses to routes
[cite:@rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim; @tang-2019-robus-sched; @li-2014-trans-bus], determining
whether a set of existing combustion based buses should be replaced with BEBs [cite:@zhou-2020-bi-objec;
@duan-2021-refor-mixed; @rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim], and accounting for uncertainties
[cite:@bie-2021-optim-elect; @duan-2021-refor-mixed; @tang-2019-robus-sched;@ursavas-2016-optim-polic]. These problems
add additional complexities that warrant simplification for the sake of computation. Two modes of simplification are
often found: only utilizing fast chargers during planning [cite:@li-2014-trans-bus; @li-2014-trans-bus;
@wang-2017-optim-rechar] or simplification of the charging models are made by assuming full charge
[cite:@zhou-2020-bi-objec; @qarebagh-2019-optim-sched; @wei-2018-optim-spatio].

Modeling the battery charge dynamics well is pertinent to this work as it directly affects the quality of the produced
schedule. Furthermore, an inaccurate model and may have detrimental affects to the health of the battery if it is
over-charged, under-charged, or forced to perform "deep" deep cycles [cite:@zhou-2020-bi-objec;
@millner-2010-model-lithium; @edge-2021-lithium]. While the charge profile for batteries are inherently non-linear, some
works have assumed a proportional charge increase as linear battery dynamics remain a valid assumption when the battery
SOC is below 80% [cite:@liu-2020-batter-elect]. Furthermore, other works have suggested that charging a battery nearly
to capacity is detrimental to the health and can significantly reduce the total charge cycles a battery may undergo
[cite:@edge-2021-lithium; @millner-2010-model-lithium]. Thus, this work assumes that a linear model is sufficiently
accurate to produce an operationally valid schedule while maintaining battery health.

Works concerning charge planning often use a version of the vehicle scheduling problem [cite:@tang-2019-robus-sched;
@li-2014-trans-bus; @he-2020-optim-charg]. Variants of this problem address infrastructure as well as determining
existing buses that should be replaced by a BEB [cite:@zhou-2020-bi-objec; @duan-2021-refor-mixed;
@rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim]. This work bases its implementation on what is known as the Position
allocation problem [cite:@qarebagh-2019-optim-sched]. The PAP is derived from the Berth Allocation Problem (BAP) which
solves the problem of scheduling a set of vessels to be berthed and serviced. The model inputs a set of vessels arrival
and service times and outputs a schedule that defines the selected berth and the time over which it is serviced. The PAP
utilizes this model and redefines its inputs to EV arrival times and outputs queues for the EVs to be charged. While the
visits remain as discrete events, the time that the BEB is on the charger is modeled as continuous, similar to
[cite:@frojan-2015-contin-berth; @qarebagh-2019-optim-sched;@zhou-2020-collab-optim]. Due to the close relationship
between the BAP and PAP, BAP literature may be used for the PAP. The literature shows methods of handling multiple quays
(sets of chargers) to handle general berthing scenarios [cite:@frojan-2015-contin-berth;@dai-2008-suppl-chain-analy].
Heuristic procedures for quicker solve times have also been introduced [cite:@imai-2001-dynam-berth]. Methods of
defining static (full-time horizon) and dynamic (rolling-time horizon) models have been created for daily and real-time
solutions, respectively, and even fuzzy set theory has been applied to allow for more flexible schedules
[cite:@bello-2019-fuzzy-activ;@dai-2008-suppl-chain-analy;@buhrkal-2011-model-discr;@frojan-2015-contin-berth]. This
work utilizes an extension of the PAP as the basis of determining the feasible space of candidate solutions.

To the best of our knowledge, there is one other work that schedule BEB fleets while allowing multiple charger types,
charger, partial charging, and accounting for consumption costs [cite:@whitaker-2023-a-network]. The work in
[cite:@whitaker-2023-a-network] presents an optimization framework that assumed a fixed schedule, utilized non-linear
battery dynamics, partial charging, considers limited charger availability, consumption cost, and allows for multiple
charger types [cite:@whitaker-2023-a-network]. This paper expands on these previous works by introducing a simulated
annealing (SA) framework that accounts for partial charging, minimizes total charger count, allows for multiple charger
types, minimizes consumption cost, and minimizes demand cost.

In what follows, the problem statement shall be provided in [[#sec:sa-problem-description]]. [[#sec:sa-optimization-problem]]
introduces the structure of the MILP formulation as well as a description of the parameters, decision variables,
objective function and constraints. In [[#sec:sa-simulated-annealing]], the concept and theory of SA is introduced. In
particular the algorithms and methods utilized for the SA implementation for this work are discussed.
[[#sec:sa-optimization-algorithm]] outlines a generic SA algorithm, and then combines the previous sections to introduce the
particular implementation for the SA-PAP. In [[#sec:sa-example]], an example problem is provided to demonstrate the capability
of the work provided in this paper. The results will be presented and discussed.
#+end_comment
