* Introduction
:PROPERTIES:
:CUSTOM_ID: sec:introduction
:END:

#+begin_comment
TODO: Add notes about work using heuristic searches for SA
#+end_comment

Public transportation systems are a critical component urban areas. An increased awareness and concern of environmental
impacts of petroleum based public transportation has driven an effort to reduce the pollutant footprint
[cite:@de-2014-simul-elect;@xylia-2018-role-charg;@guida-2017-zeeus-repor-europ;@li-2016-batter-elect]. Particularly,
the electrification of public bus transportation via battery power, i.e., battery electric buses (BEBs), has received
significant attention [cite:@li-2016-batter-elect]. Although the technology provides benefits beyond reduction in
emissions, such as lower driving costs, lower maintenance costs, and reduced vehicle noise, battery powered systems
introduce new challenges such as larger upfront costs, and potentially several hours long "refueling" periods
[cite:@xylia-2018-role-charg;@li-2016-batter-elect]. Furthermore, the problem is exacerbated by the constraints of the
transit schedule to which the fleet must adhere, the limited amount of chargers available, and the adverse affects in
the health of the battery due to fast charging [cite:@lutsey-2019-updat-elect]. This work presents a scheduling
framework for a fixed-schedule fleet of BEBs that utilizes a proportional battery dynamics model, accounts for multiple
charger types, allows partial charging, and further considers the total energy consumed by the schedule as well as peak
power use.

Literature shows an interest in solving the problem of assigning BEBs to charging queues or optimizing their
infrastructure [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;
@hoke-2014-accoun-lithium;@wang-2017-elect-vehic]. Additionally, the prospect of solving both problems simultaneously
has received much attention [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;
@hoke-2014-accoun-lithium;@wang-2017-elect-vehic]. These problems vary by including assignment of buses to routes
[cite:@rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim; @tang-2019-robus-sched; @li-2014-trans-bus], determining
whether a set of existing combustion based buses should be replaced with BEBs [cite:@zhou-2020-bi-objec;
@duan-2021-refor-mixed; @rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim], and accounting for uncertainties
[cite:@bie-2021-optim-elect; @duan-2021-refor-mixed; @tang-2019-robus-sched;@ursavas-2016-optim-polic]. These problems
add additional complexities that warrant simplifications for the sake of computation. Two modes of simplification are
often found: only utilizing fast chargers during planning [cite:@li-2014-trans-bus; @li-2014-trans-bus;
@wang-2017-optim-rechar] or simplification of the charging models are made by assuming full charge
[cite:@zhou-2020-bi-objec; @qarebagh-2019-optim-sched; @wei-2018-optim-spatio].

Modeling the battery charge dynamics well is pertinent to this work as it directly affects the quality of the produced
schedule. Furthermore, an inaccurate model and may have detrimental affects to the health of the battery if it is
over-charged, under-charged, or forced to perform "deep" deep cycles [cite:@zhou-2020-bi-objec;
@millner-2010-model-lithium; @edge-2021-lithium]. While the charge profile for batteries are inherently non-linear, some
works have assumed a proportional charge increase as linear battery dynamics remain a valid assumption when the battery
SOC is below 80% [cite:@liu-2020-batter-elect]. Furthermore, other works have suggested that charging a battery nearly
to capacity is detrimental to the health and can significantly reduce the total charge cycles a battery may undergo
[cite:@edge-2021-lithium; @millner-2010-model-lithium]. Thus, this work assumes that a linear model is sufficiently
accurate to produce an operationally valid schedule while maintaining battery health.

Works concerning charge planning often use a version of the vehicle scheduling problem [cite:@tang-2019-robus-sched;
@li-2014-trans-bus; @he-2020-optim-charg]. Variants of this problem address infrastructure as well as determining
existing buses that should be replaced by a BEB [cite:@zhou-2020-bi-objec; @duan-2021-refor-mixed;
@rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim]. This work bases its implementation on what is known as the Position
allocation problem [cite:@qarebagh-2019-optim-sched]. The PAP is derived from the Berth Allocation Problem (BAP) which
solves the problem of scheduling a set of vessels to be berthed and serviced. The model inputs a set of vessels arrival
and service times and outputs a schedule that defines the selected berth and the time over which it is serviced. The PAP
utilizes this model and redefines its inputs to EV arrival times and outputs queues for the EVs to be charged. While the
visits remain as discrete events, the time that the BEB is on the charger is modeled as continuous, similar to
[cite:@frojan-2015-contin-berth; @qarebagh-2019-optim-sched;@zhou-2020-collab-optim]. Due to the close relationship
between the BAP and PAP, BAP literature may be used for the PAP. The literature shows methods of handling multiple quays
(sets of chargers) to handle general berthing scenarios [cite:@frojan-2015-contin-berth;@dai-2008-suppl-chain-analy].
Heuristic procedures for quicker solve times have also been introduced [cite:@imai-2001-dynam-berth]. Methods of
defining static (full time horizon) and dynamic (rolling-time horizon) models have been created for daily and real-time
solutions, respectively, and even fuzzy set theory has been applied to allow for more flexible schedules
[cite:@bello-2019-fuzzy-activ;@dai-2008-suppl-chain-analy;@buhrkal-2011-model-discr;@frojan-2015-contin-berth]. This
work utilizes an extension of the PAP as the basis of determining the feasible space of candidate solutions.

To the best of our knowledge, there is one other work that schedule BEB fleets while allowing multiple charger types,
charger, partial charging, and accounting for consumption costs [cite:@whitaker-2023-a-network]. The work in
[cite:@whitaker-2023-a-network] presents an optimization framework that assumed a fixed schedule, utilized non-linear
battery dynamics, partial charging, considers limited charger availability, consumption cost, and allows for multiple
charger types [cite:@whitaker-2023-a-network]. This paper expands on these previous works by introducing a simulated
annealing (SA) framework that accounts for partial charging, minimizes total charger count, allows for multiple charger
types, minimizes consumption cost, and minimizes demand cost.

In what follows, the problem statement shall be provided in [[#sec:problem-description]]. [[#sec:optimization-problem]]
introduces the structure of the MILP formulation as well as a description of the parameters, decision variables,
objective function and constraints. In [[#sec:simulated-annealing]], the concept and theory of SA is introduced. In
particular the algorithms and methods utilized for the SA implementation for this work are discussed.
[[#sec:optimization-algorithm]] outlines a generic SA algorithm, and then combines the previous sections to introduce the
particular implementation for the SA-PAP. In [[#sec:example]], an example problem is provided to demonstrate the capability
of the work provided in this paper. The results will be presented and discussed.
