* Problem Description
:PROPERTIES:
:CUSTOM_ID: sec:problem-description
:END:
It is assumed that there are a total of $I$ visits to the station by $B$ buses. There are a total of $Q$ queues for the
bus at the station. Given a set of bus arrivals to a charging station $i \in \{1,..., I\} = \Iset \subset \mathcal{Z}$ with a set of
chargers to be queued $q \in \{1,..., Q\} = \Qset \subset \mathcal{Z}$ where the bus is indicated by an identification number $b \in
\{1,..., B\} = \Bset \subset \mathcal{Z}$. Each bus arrival, $i$, can be represented by the tuple: $\visit$, in which the ordered
elements denote the bus identification number, $b_i$, arrival time to the station, $a_i$, departure time from the
station, $e_i$, time to start charging, $u_i$, time to stop charging, $d_i$, the charger queue for the bus to be placed
into, $v_i$, and the initial State Of Charge (SOC), $\eta_i$.

It is assumed that each visit occurs over the time horizon $T = \{t : t_0 \le t \le t_f \}$. The set of all arrivals is
represented by the set $\I = \{\forall i \in \Iset \; \visit: b_i, \xi_i \in \Bset, a_i, e_i, u_i, d_i \in T, v_i \in \Qset \}$. The
concept of "arrivals" is derived from the PAP [[cite:&qarebagh-2019-optim-sched]]. This idea of arrivals is useful in the
sense that it is easy to describe the state of any arbitrary arrival; however, although a bus may revisit the station
multiple times, the model assumes that each arrival is unique (i.e. no two bus arrives twice) therefore a system must be
put in place to track each bus over each arrival. That is why a bus identifier is placed in the tuple, and in that way
each bus can be tracked over each arrival.

For each arrival a bus must be placed in a singular queue, $v_i \in \Qset$. The charger $q$ is assumed to be either a fast
or slow charger or no charger at all. A bus is only allowed to visit one queue per visit; however, there may be multiple
buses charging simultaneously. The amount of time the bus is allowed to charge is dictated by the scheduled arrival time
and required departure time, $[a_i, e_i]$. Although a bus must be placed in a queue, if a bus does not require much
charge, or none at all, partial charges, or no charging, is allowed. It is not allowed for the bus to charge over its
battery capacity limit. The battery charging rate is modeled as linear, which remains accurate up to about an SOC of 80%
charge [[cite:li-2016-batter-elect]].

Each bus arrival, with the exception of the last arrival for each bus, has a paired "route" that the bus must perform.
This route, as one would expect, causes the bus to discharge by some certain amount. This paper assumes an average
discharge over a period of in which an estimated discharge is calculated for each route, $\Delta_i$. The charge supplied
while at the station is required to supply enough charge for each route (battery charge does not deplete to zero) with
an additional battery capacity percentage, $m$, acting as a safety factor.

The scheduler's task shall be to schedule the set of arrivals $\I$ to fulfill the minimum charge requirements over the
time horizon $T$ as well as minimize the demand cost as well as minimize over the consumption cost. The objective
function and constraints are discussed in further detail in section [[#sec:objective-function]].