name: LaTeX Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build PDF"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update and Intall Dependencies 
      run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
    - name: Setup go-task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Clean Project
      run: task clean
    - name: PlantUML
      uses: holowinski/plantuml-github-action@main
      with:
        args: -v -tpng "sections/img/*.pml"
    - name: Build PDF
      run: task
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./sa-pap.pdf
