name: LaTeX Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build PDF"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Update and Intall Dependencies
      run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
    - name: Clean Project
      run: make clean
    - name: List Project
      run: ls -R
    - name: PlantUML
      uses: holowinski/plantuml-github-action@main
      with:
        args: -v -tpng "sections/img/*.pml"
    - name: Build PDF
      run: make
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./sa-pap.pdf
