name: LaTeX Release

permissions:
  contents: write

on:
  push:
    tags: 'v*.**'

jobs:
  pre-release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Update and Intall Dependencies
      run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
    - name: Clean Project
      run: make clean
    - name: PlantUML
      uses: holowinski/plantuml-github-action@main
      with:
        args: -v -tpng "img/*.pml"
    - name: Build PDF
      run: make pipeline
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "sa-pap.pdf"
        bodyFile: "README.org"
