name: LaTeX Release

on:
  push:
    tags: 'v*.**'

jobs:
  pre-release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update and Intall Dependencies 
      run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
    - name: Setup go-task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Plantuml
      uses: cloudbees/plantuml-github-action@master
      with:
        args: -v -tpng ./sections/img/*.puml
    - name: Build PDF
      run: task clean && task
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "sa-pap.pdf"
        # bodyFile: "README.org"
